CREATE USER sandbox_user WITH PASSWORD 'sandbox_password' INHERIT CREATEDB CREATEROLE LOGIN;
CREATE SCHEMA sandbox;
GRANT ALL PRIVILEGES ON SCHEMA sandbaox TO sandbox_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sandbox TO sandbox_user;
